# Create a database with the name 'accounts'
# ubuntu@ip-172-31-43-201:~/vprofile/exercise6$ cat web-db.yaml
- name: webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: Start service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
# Adding copy files to remote location Module
    - name: Copy index file
      copy:
        src: files/index.html
        dest: /var/www/html/index.html


- name: DBServer setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present
# This install PyMySQL and resolves the error
    - name: Install pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present
    - name: Start maria service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
# This creates a database with name accounts
    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present
# This added  the sock path
        login_unix_socket: /var/lib/mysql/mysql.sock

