# ubuntu@ip-172-31-43-201:~/vprofile/exercise6$ cat web-db5.yaml
- name: DBServer setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Start maria service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

# Install PyMySQL for Python 3
    - name: Install PyMySQL
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Create .my.cnf file
      become: yes
      copy:
        content: |
          [client]
          user = root
          password = your_root_password
        dest: /root/.my.cnf
        mode: '0600'


# Creating a new database name 'accounts'
    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present

